Feature/order was created event
funeralzone/calfords pull request #1
Opened 2019-08-15 08:31 UTC by sangheethan

When this PR is merged it will:
- create a new Order entity
- update the list of value objects on the events.yml file
- create a new model.yml file which will list all the types for the value objects.
- run 2 test cases to test the order amount.

2019-08-15 11:04 UTC, chrisharrison commented on src/Model/Order/OrderTest.php
> +		$amount->negative();
`negative()` returns an immutable money object.

https://github.com/moneyphp/money/blob/master/src/Money.php#L477

2019-08-15 11:14 UTC, sangheethan commented on src/Model/Order/OrderTest.php
> +		$amount->negative();
Yes, I haven't use it. So will delete those 2 lines.

2019-08-15 11:22 UTC, matt-t-d requested changes

2019-08-15 11:22 UTC, mattythebatty commented on src/Model/Order/OrderTest.php
> +    public function test_order_amount_cannot_be_zero()
The test says the amount can't be 0 but the code asserts it is 0

2019-08-15 11:22 UTC, mattythebatty commented on src/Model/Order/Order.php
> +	use ApplyDeltaTrait;
tabs are being used instead of spaces

2019-08-15 11:33 UTC, chrisharrison commented
I really like the PR description "When this PR is merged it will" and the detail in describing what the PR consists of.

2019-08-15 11:34 UTC, centralhawk3 commented on src/Model/Order/Order.php
> +namespace Funeralzone\calfords\Model\Order;
Just for consistency reasons calfords should have an uppercase C at the beginning.

2019-08-15 11:38 UTC, centralhawk3 commented on src/Model/Order/Order.php
> +				'businessName' => $businessName,
Every element within the event payload should use its native type. Therefore, `$businessName` for example should be `$businessName->toNative()` as ultimately the payload will be serialised into a JSON string.

2019-08-15 11:39 UTC, mattythebatty commented
> I really like the PR description "When this PR is merged it will" and the detail in describing what the PR consists of.

I agree although I would suggest the commit message be simpler - at least the first line of it. Currently when looking through the [commits](https://github.com/funeralzone/calfords/pull/1/commits) it would just show "When this commit is applied it will:".

For the commit message I would say that "create Order aggregate" would be enough here. The files changed wouldn't need to mentioned specifically because we can see them in the diff

2019-08-15 11:47 UTC, centralhawk3 commented on src/Model/Order/OrderTest.php
> +		$order = Order::create(
You could use your `getAggregate` method here and simply pass in ```[
				"amount" => -50,
				"currency" => "GBP"
			]``` instead of having to create an entire new order.

2019-08-15 11:49 UTC, centralhawk3 requested changes
A few comments were left on individual files by me.

2019-08-15 11:56 UTC, centralhawk3 commented
> > I really like the PR description "When this PR is merged it will" and the detail in describing what the PR consists of.
> 
> I agree although I would suggest the commit message be simpler - at least the first line of it. Currently when looking through the [commits](https://github.com/funeralzone/calfords/pull/1/commits) it would just show "When this commit is applied it will:".
> 
> For the commit message I would say that "create Order aggregate" would be enough here. The files changed wouldn't need to mentioned specifically because we can see them in the diff
Agreed. I tend to think of it in terms of how the PR's goal will be achieved. For example:

"When this PR is merged it will create the order aggregate. The following steps will occur in order to achieve this: 1) It will apply the results of the domain modelling session. 2) etc..."

2019-08-15 12:38 UTC, nealstammers commented on src/Model/Order/Order.php
> +	private $amount;
Would we want to, above each variable, include for example
`/** @var OrderAmount $amount **/`

2019-08-15 12:40 UTC, nealstammers commented on src/Model/Order/Order.php
> +	public static function fromNative(array $native)
return type `: self` ?

2019-08-15 12:41 UTC, nealstammers commented on src/Model/Order/Order.php
> +	{
I think for PSR2 the opening `{` will need to be on the same line above, e.g. `): Order {`

2019-08-15 12:44 UTC, nealstammers commented on src/Model/Order/OrderTest.php
We usually include `// @codingStandardsIgnoreFile` at the top of a test file

2019-08-15 12:55 UTC, nealstammers commented on src/Model/Order/Order.php
> +	public static function create(
I believe the properties of the create method should be ValueObjects, so something like:
```
public static function create(
    OrderId $id,
    BusinessName $businessName,
    ...
): Order { ...
```

2019-08-15 12:57 UTC, nealstammers commented on src/Model/Order/OrderTest.php
> +			"Jimmy's car rental",
If you do stick with using the create method directly here, you'll need to supply ValueObjects for each of the properties (see the change to the aggregate, mentioned above)

2019-08-15 13:03 UTC, nealstammers commented on src/Model/Order/Order.php
> +		$instance->recordThat(
In order for the test `can't create an order with a negative value / zero value` would you want to do something like:
```
if ($amount->isNegative() || $amount === 0) {
    throw new OrderAmountMustBeGreaterThanZero($amount); // this exception would also need to be added
}
```

2019-08-15 13:06 UTC, nealstammers commented on src/Model/Order/OrderTest.php
> +		$order = Order::create(
If you throw an exception in the create method, you can test for it here:
`$this->expectException(OrderAmountMustBeGreaterThanZero::class);`

2019-08-15 13:08 UTC, nealstammers commented
I added a single exception, `OrderAmountMustBeGreaterThanZero`, but considering what @chrisharrison mentioned the other day about it being two rules (not negative, AND not zero) it could be better creating two exceptions. One for each case. Then, if the business rules change and allow for zero value orders, it would be fairly straight forward to remove the specific checks/exception)

2019-08-15 13:26 UTC, mattythebatty commented
I'm not sure how PhpStorm is set up on your computer but you can set it to use PSR 2 which will handle most of the formatting automatically for you.
![image](https://user-images.githubusercontent.com/2466044/63097517-8b889980-bf68-11e9-919b-9606bc1a1edd.png)
You can use the shortcut Ctrl+Alt+L (not sure if it's the same on mac) to reformat whole files.

2019-08-16 08:06 UTC, sangheethan commented on src/Model/Order/OrderTest.php
> +		$order = Order::create(
I removed the getAggregate method and created an entire new order so that the create method is called and the expected exception is caught.

2019-08-16 08:34 UTC, mattythebatty commented on src/Model/Order/Exceptions/OrderAmountMustBeGreaterThanZero.php
> +namespace Funeralzone\Calfords\Model\Order\Exceptions;
There are a couple of things in this file that can be prevented by changing some settings in PhpStorm. In the settings you can configure the template for new files and classes. 
e.g.

![image](https://user-images.githubusercontent.com/2466044/63153928-67c86080-c007-11e9-9213-034deb392434.png)

The things in this file are:

- [ ] `declare(strict_types=1);`
- [ ] line breaks around namespace
- [ ] use spaces instead of tabs

2019-08-16 08:42 UTC, sangheethan commented on src/Model/Order/Order.php
> +	use ApplyDeltaTrait;
How many spaces should I be using instead of tabs?

2019-08-16 08:52 UTC, mattythebatty commented on src/Model/Order/Order.php
> +	use ApplyDeltaTrait;
4 spaces. PhpStorm should be able to automatically update files and automatically convert tabs. You can set it here:
![image](https://user-images.githubusercontent.com/2466044/63155913-803a7a00-c00b-11e9-86f9-879f42e14f42.png)

2019-08-16 10:13 UTC, closed without merging

2019-08-16 10:55 UTC, nealstammers commented on src/Model/Order/OrderTest.php
> +		$this->createOrder(-50);
Hey Sang, this is looking loads better. However, you may want to consider explicitly using `Order::create(...)` in each of the tests. (there's no harm in duplicating the code)

It's very likely that we'll need to test different variations of data being passed to the create method; at the moment, you've locked it down to only being able to accept `$amount`. When a new variable needs testing, you'll need to modify the `createOrder` method, and any tests which are currently using it.

I don't know what others think, but I quite like being explicit with a variable at the top of the test, e.g.
```
$amount = -50;

$this->expectException(OrderAmountMustNotBeNegative::class);
Order::create(
            OrderId::generate(),
            ...
            OrderAmount::fromNative([
                "amount" => $amount,
                "currency" => "gbp"
            ])
        );
```

2019-08-16 10:58 UTC, nealstammers commented on src/Model/Order/Order.php
> +		OrderId $id,
Sorry Sang, I didn't spot/mention that all these are required, so we should be using the NonNull versions. e.g. 
`NonNullOrderId $Id`, etc